name: osym
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5 
  google_sign_in: ^6.3.0 
  go_router: ^14.8.1
  font_awesome_flutter: ^10.8.0
  flutter_dotenv: ^5.2.1  
  flutter_markdown: ^0.7.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0 
  syncfusion_flutter_charts: ^29.1.38
  intl: ^0.19.0
  path_provider: ^2.1.5
  collection: ^1.19.1
  webview_flutter: ^4.11.0 
  html: ^0.15.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
   
  assets:
    - assets/
    - assets/lesson_links.json
    - assets/topics_questions.json
    - assets/lesson_topics.json
    - .env 
  